# Generated by Django 5.0.2 on 2024-02-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_registration_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
    ]
