# Generated by Django 5.0.2 on 2024-02-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_registration_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=15)),
                ('product_price', models.IntegerField()),
                ('product_image', models.FileField(upload_to='')),
            ],
        ),
    ]
