# Generated by Django 5.0.2 on 2024-02-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_productdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='product_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
