# Generated by Django 5.0.2 on 2024-02-27 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_registration_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.productdetails')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.registration')),
            ],
        ),
    ]
