# Generated by Django 5.0.2 on 2024-03-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
