# Generated by Django 5.0.2 on 2024-03-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
