# Generated by Django 5.0.2 on 2024-03-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_productdetails_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
