# Generated by Django 5.0.2 on 2024-04-01 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliverydetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=20)),
                ('Pincode', models.IntegerField()),
                ('state', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=40)),
                ('Breed_details_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.productdetails')),
                ('user_details_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.registration')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
