# Generated by Django 5.0.2 on 2024-04-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_deliverydetails_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverydetails',
            old_name='Breed_details_2',
            new_name='productdetails_2',
        ),
        migrations.RenameField(
            model_name='deliverydetails',
            old_name='user_details_2',
            new_name='userdetails',
        ),
    ]
