# Generated by Django 5.0.2 on 2024-04-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_rename_breed_details_2_deliverydetails_productdetails_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='Pincode',
            field=models.CharField(max_length=10),
        ),
    ]
