# Generated by Django 5.0.2 on 2024-04-16 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_deliverydetails_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('ordered_quantity', models.PositiveIntegerField(default=1)),
                ('instruction', models.CharField(default='Your Order Has Been Successfully Placed', max_length=50, null=True)),
                ('product_status', models.CharField(default='Order Placed', max_length=50, null=True)),
                ('status_message', models.CharField(blank=True, max_length=255, null=True)),
                ('item_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.productdetails')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.registration')),
            ],
        ),
    ]
