# Generated by Django 5.0.2 on 2024-04-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_productdetails_product_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
