# Generated by Django 5.0.2 on 2024-05-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_orders_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='instruction',
            field=models.CharField(default='Your Order Has Been Successfully Placed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='payment_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='product_status',
            field=models.CharField(default='paid', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
