# Generated by Django 5.0.2 on 2024-05-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_delete_orders_deliverydetails_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='city',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
