# Generated by Django 5.0.2 on 2024-05-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_deliverydetails_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='product_status',
            field=models.CharField(default='Order placed', max_length=50, null=True),
        ),
    ]
