# Generated by Django 5.0.2 on 2024-05-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_alter_deliverydetails_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='payment_status',
            field=models.CharField(default=True, max_length=20, null=True),
        ),
    ]
