# Generated by Django 5.0.2 on 2024-05-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_alter_deliverydetails_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
