# Generated by Django 5.0.2 on 2024-05-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_productdetails_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='payment_status',
            field=models.CharField(default='TRUE', max_length=20, null=True),
        ),
    ]
