# Generated by Django 5.0.2 on 2024-05-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_alter_deliverydetails_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='product_quantity',
        ),
    ]
