# Generated by Django 5.0.2 on 2024-05-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_remove_productdetails_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='product_stock',
            field=models.IntegerField(default=1),
        ),
    ]
